# Generated by Django 2.0.1 on 2018-07-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20180702_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_telephone',
            field=models.CharField(max_length=11),
        ),
    ]
