# Generated by Django 2.0.1 on 2018-07-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20180702_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_name',
            field=models.CharField(default=1, max_length=160),
        ),
    ]
