# Generated by Django 2.0.1 on 2018-07-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_schedule_schedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='123456', max_length=160),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
