# Generated by Django 2.0.1 on 2018-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_auto_20180704_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
