# Generated by Django 2.0.1 on 2018-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_auto_20180704_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
