# Generated by Django 2.0.1 on 2018-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_accesscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[('教师', 1), ('学生', 0)], default=0, max_length=10, verbose_name='User Type'),
        ),
    ]
