# Generated by Django 2.0.1 on 2018-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(1, '教师'), (0, '学生')], default=0, max_length=10, verbose_name='User Type'),
        ),
    ]
