# Generated by Django 2.0.1 on 2018-08-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0013_auto_20180821_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessControl',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='score',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
