# Generated by Django 2.0.1 on 2018-08-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0015_auto_20180821_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='type',
            new_name='user_type',
        ),
    ]
