# Generated by Django 2.0.1 on 2018-09-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0019_auto_20180906_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='level',
            field=models.CharField(choices=[(0, 'Null'), (9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], max_length=2),
        ),
    ]
