# Generated by Django 2.0.1 on 2018-09-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0023_auto_20180906_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='level',
            field=models.IntegerField(choices=[(0, 'Null'), (6, 'A+'), (5, 'A'), (4, 'B+'), (3, 'B'), (2, 'C+'), (1, 'C')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'assignment')},
        ),
    ]
