# Generated by Django 2.0.1 on 2018-09-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0024_auto_20180909_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='student',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='begin_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='term',
            field=models.IntegerField(blank=True, choices=[(1, '第一学年上学期'), (2, '第一学年下学期'), (3, '第二学年上学期'), (4, '第二学年下学期'), (5, '第三学年上学期'), (6, '第三学年下学期')], null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Total',
        ),
    ]
