# Generated by Django 2.0.1 on 2018-09-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0026_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
