# Generated by Django 2.0.1 on 2018-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0027_score_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='total',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='score',
            name='level',
            field=models.IntegerField(choices=[(0, 'Null'), (10, 'A+'), (8, 'A'), (6, 'B+'), (4, 'B'), (2, 'C+'), (1, 'C')], default=0),
        ),
    ]
